# Deep Learning Method

In [12]:
import os
import numpy as np
import pandas as pd

In [13]:
df = pd.read_pickle("/content/cleaned_tweets_v1.pkl")
df.head()

label  ...                   cleaned_tweets_without_stopwords
0      1  ...  fingerprint pregnancy test android apps beauti...
1      1  ...  finally transparant silicon case thanks uncle ...
2      1  ...  love talk makememories unplug relax iphone sma...
3      1  ...    wired know george way iphone cute daventry home
4      0  ...  amazing service apple talk question unless pay...

[5 rows x 4 columns]

In [3]:
# Split the data into independent and dependent features
x = df.drop('label', axis=1)
y = df['label']

In [4]:
x.head(2)

tweet  \
0  #fingerprint #Pregnancy Test https://goo.gl/h1...   
1  Finally a transparant silicon case ^^ Thanks t...   

                                      cleaned_tweets  \
0  fingerprint pregnancy test android apps beauti...   
1  finally transparant silicon case thanks uncle ...   

                    cleaned_tweets_without_stopwords  
0  fingerprint pregnancy test android apps beauti...  
1  finally transparant silicon case thanks uncle ...

In [5]:
import tensorflow as tf
from tensorflow.keras.layers import LSTM, GRU, Bidirectional, Dense, Dropout, Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
# Vocab size
voc_size=1000

In [7]:
df.columns

Index(['label', 'tweet', 'cleaned_tweets', 'cleaned_tweets_without_stopwords'], dtype='object')

In [8]:
df['cleaned_tweets_without_stopwords'][0]

'fingerprint pregnancy test android apps beautiful cute health igers iphoneonly iphonesia iphone'

In [9]:
df['cleaned_tweets_without_stopwords'][2500]

'secure study show malware pc come pdf exploit apple user'

In [11]:
df['cleaned_tweets_without_stopwords'][100]

'dreamy effect created straight iphone impressive spring flower blossom'

In [7]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [14]:
len(x)

7920

In [8]:
x['cleaned_tweets_without_stopwords'][0]

'fingerprint pregnancy test android apps beautiful cute health igers iphoneonly iphonesia iphone'

In [9]:
# Data Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []

for i in range(0, len(x)):
  print(i)
  review = re.sub('[^a-zA-Z]',' ', x['cleaned_tweets_without_stopwords'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963
2964
2965
2966
2967
2968
2969
2970
2971
2972
2973
2974
2975
2976
2977
2978
2979
2980
2981
2982
2983
2984
2985
2986
2987
2988
2989
2990
2991
2992
2993
2994
2995
2996
2997
2998
2999
3000
3001
3002
3003
3004
3005
3006
3007
3008
3009
3010
3011
3012
3013
3014
3015
3016
3017
3018
3019
3020
3021
3022
3023
3024
3025
3026
3027
3028
3029
3030
3031
3032
3033
3034
3035
3036
3037
3038
3039
3040
3041
3042
3043
3044
3045
3046
3047
3048
3049
3050
3051
3052
3053
3054
3055
3056
3057
3058
3059
3060
3061
3062
3063
3064
3065
3066
3067
3068
3069
3070
3071
3072
3073
3074
3075
3076
3077
3078
3079
3080
3081
3082
3083
3084
3085
3086
3087
3088
3089
3090
3091
3092
3093
3094
3095
3096
3097
3098
3099
3100
3101
3102
3103
3104
3105
3106
3107
3108
3109

In [10]:
corpus

['fingerprint pregnanc test android app beauti cute health iger iphoneonli iphonesia iphon',
 'final transpar silicon case thank uncl yay soni xperia sonyexperia',
 'love talk makememori unplug relax iphon smartphon wifi connect',
 'wire know georg way iphon cute daventri home',
 'amaz servic appl talk question unless pay stupid support',
 'iphon softwar updat fuck phone big time stupid iphon',
 'happi instap instadaili soni xperia xperiaz',
 'new type charger cabl bay amazon etsi new year rob cross tobi young evemun mcmafia taylor spectr newyear start recip technolog samsunggalaxi iphonex pic pjiwq wtc',
 'bout shop listen music iphon justm music likeforlik followforfollow',
 'photo fun selfi pool water soni camera picoftheday sun instagood boy cute outdoor',
 'hey appl make new ipod make new color inch thinner make crash fuckin minit',
 'heavi machineri need realli drop ball design drinkyourhaterad',
 'contempl give iphon bandwagon simpli cellcom new android depress idontwantto',
 'c

In [11]:
onehot_repr = [one_hot(words, voc_size) for words in corpus]
onehot_repr

[[478, 234, 409, 385, 142, 37, 691, 187, 395, 678, 233, 632],
 [466, 875, 588, 295, 201, 293, 136, 347, 689, 485],
 [305, 748, 144, 444, 27, 632, 584, 861, 852],
 [870, 295, 843, 90, 632, 691, 461, 444],
 [271, 272, 974, 748, 157, 878, 858, 475, 762],
 [632, 140, 932, 849, 872, 473, 793, 475, 632],
 [91, 84, 93, 347, 689, 363],
 [812,
  67,
  503,
  887,
  241,
  414,
  394,
  812,
  921,
  478,
  90,
  273,
  110,
  455,
  176,
  708,
  817,
  995,
  933,
  155,
  693,
  871,
  597,
  758,
  144,
  264],
 [289, 117, 750, 818, 632, 510, 818, 12, 149],
 [113, 873, 437, 436, 262, 347, 475, 577, 249, 674, 516, 691, 318],
 [502, 974, 231, 812, 945, 231, 812, 131, 548, 182, 231, 72, 525, 429],
 [183, 508, 279, 932, 872, 320, 325, 949],
 [445, 422, 632, 972, 664, 56, 812, 385, 622, 771],
 [558, 443, 546, 166, 285, 821, 777, 821, 546, 833, 974, 117],
 [33, 663, 177, 901, 251, 321, 663, 809, 732],
 [425, 699, 719, 40, 148, 347, 214, 378],
 [933, 510, 522, 872, 295, 632, 632, 758, 133, 276],
 [

In [12]:
sent_length = 20
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[  0   0   0 ... 678 233 632]
 [  0   0   0 ... 347 689 485]
 [  0   0   0 ... 584 861 852]
 ...
 [  0   0   0 ... 834 279 251]
 [  0   0   0 ... 833 200 749]
 [  0   0   0 ... 509 873 444]]


In [19]:
len(embedded_docs)

7920

In [20]:
y.shape

(7920,)

In [13]:
y

0       1
1       1
2       1
3       1
4       0
       ..
7915    1
7916    1
7917    1
7918    1
7919    1
Name: label, Length: 7920, dtype: int64

In [15]:
embedded_docs[0]

array([  0,   0,   0,   0,   0,   0,   0,   0, 478, 234, 409, 385, 142,
        37, 691, 187, 395, 678, 233, 632], dtype=int32)

In [16]:
x_final = np.array(embedded_docs)
y_final = np.array(y)

In [17]:
y_final.shape, y_final.shape

((7920,), (7920,))

In [33]:
y_final.dtype

dtype('int64')

In [30]:
y_final.dtype

dtype('int64')

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, test_size=0.2, random_state=42, stratify=y_final)


In [38]:
y_test

array([1, 0, 1, ..., 1, 0, 1])

# Building LSTM model for training and evaluation purpose

In [21]:
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model.add(LSTM(100))
model.add(Dropout(0.4))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=32, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


198/198 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7646 - loss: 0.5090 - val_accuracy: 0.8422 - val_loss: 0.3406
Epoch 2/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8873 - loss: 0.2628 - val_accuracy: 0.8510 - val_loss: 0.3283
Epoch 3/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9076 - loss: 0.2232 - val_accuracy: 0.8466 - val_loss: 0.3438
Epoch 4/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9128 - loss: 0.2096 - val_accuracy: 0.8434 - val_loss: 0.3522
Epoch 5/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9208 - loss: 0.1935 - val_accuracy: 0.8472 - val_loss: 0.3769
Epoch 6/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9260 - loss: 0.1892 - val_accuracy: 0.8453 - val_loss: 0.4417
Epoch 7/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9321 - loss: 0.1707 - val_accuracy: 0.8422 - val_loss: 0.4920
Epoch 8/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9411 - loss: 0.1479 - val_accuracy: 0.8371 - val_

# GRU

In [22]:
embedding_vector_features = 40
model1 = Sequential()
model1.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model1.add(GRU(100))
model1.add(Dropout(0.4))
model1.add(Dense(1, activation='sigmoid'))
model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model1.fit(x_train, y_train, batch_size=32, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7711 - loss: 0.4882 - val_accuracy: 0.8428 - val_loss: 0.3385
Epoch 2/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8816 - loss: 0.2733 - val_accuracy: 0.8516 - val_loss: 0.3459
Epoch 3/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8940 - loss: 0.2437 - val_accuracy: 0.8491 - val_loss: 0.3431
Epoch 4/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9049 - loss: 0.2252 - val_accuracy: 0.8441 - val_loss: 0.3890
Epoch 5/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9175 - loss: 0.1980 - val_accuracy: 0.8396 - val_loss: 0.4220
Epoch 6/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.9167 - loss: 0.2027 - val_accuracy: 0.8460 - val_loss: 0.3904
Epoch 7/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9260 - loss: 0.1873 - val_accuracy: 0.8428 - val_loss: 0.4354
Epoch 8/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9365 - loss: 0.1679 - val_accuracy: 0.

# Bidirectional LSTM and GRU

In [23]:
embedding_vector_features = 40
model1 = Sequential()
model1.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model1.add(Bidirectional(GRU(100)))
model1.add(Dropout(0.4))
model1.add(Dense(1, activation='sigmoid'))
model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model1.fit(x_train, y_train, batch_size=32, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


198/198 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.7784 - loss: 0.4940 - val_accuracy: 0.8460 - val_loss: 0.3369
Epoch 2/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8792 - loss: 0.2630 - val_accuracy: 0.8479 - val_loss: 0.3574
Epoch 3/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9008 - loss: 0.2354 - val_accuracy: 0.8510 - val_loss: 0.3451
Epoch 4/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9094 - loss: 0.2150 - val_accuracy: 0.8491 - val_loss: 0.3588
Epoch 5/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9122 - loss: 0.2115 - val_accuracy: 0.8472 - val_loss: 0.4075
Epoch 6/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9263 - loss: 0.1828 - val_accuracy: 0.8428 - val_loss: 0.3952
Epoch 7/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9361 - loss: 0.1654 - val_accuracy: 0.8384 - val_loss: 0.4452
Epoch 8/10
198/198 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9485 - loss: 0.1493 - val_accuracy: 0.8390 - val_

In [24]:
from tensorflow.keras.layers import *

In [26]:
embedding_vector_features = 40
model3 = Sequential()
model3.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model3.add(Bidirectional(LSTM(100)))
model3.add(Dropout(0.4))
#model3.add(BatchNormalization())
model3.add(Dense(1, activation='sigmoid'))
model3.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model3.fit(x_train, y_train, batch_size=32, epochs=5, validation_data=(x_test, y_test))

Epoch 1/5
198/198 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.7791 - loss: 0.4865 - val_accuracy: 0.8529 - val_loss: 0.3306
Epoch 2/5
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8838 - loss: 0.2664 - val_accuracy: 0.8542 - val_loss: 0.3268
Epoch 3/5
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9092 - loss: 0.2257 - val_accuracy: 0.8453 - val_loss: 0.3573
Epoch 4/5
198/198 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9112 - loss: 0.2134 - val_accuracy: 0.8365 - val_loss: 0.3695
Epoch 5/5
198/198 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9199 - loss: 0.1951 - val_accuracy: 0.8466 - val_loss: 0.3894


# Transformers model - Context Based Language Model or Large Language Model

In [6]:
#!pip install transformers

In [5]:
#!pip install datasets

In [3]:
from transformers import pipeline

In [1]:
from datasets import load_dataset

In [4]:
classification = pipeline("text-classification")


No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


In [32]:
x.columns

Index(['tweet', 'cleaned_tweets', 'cleaned_tweets_without_stopwords'], dtype='object')

In [33]:
x['cleaned_tweets_without_stopwords'][0]

'fingerprint pregnancy test android apps beautiful cute health igers iphoneonly iphonesia iphone'

In [34]:
x['cleaned_tweets_without_stopwords'][2500]

'secure study show malware pc come pdf exploit apple user'

In [35]:
classification(x['cleaned_tweets_without_stopwords'][2500])

[{'label': 'NEGATIVE', 'score': 0.9929688572883606}]

In [36]:
classification(x['cleaned_tweets_without_stopwords'][0])

[{'label': 'POSITIVE', 'score': 0.9834354519844055}]

In [9]:
review = """IN WHOLESOME ENTERTAINER,POORA PAISA VASOOL DHAMAKEDAR EXPERIENCE ,a perfect Horror comedy with all the elements right in place with horror comedy blend, Emotions, Fun , Great BGM , Excellent Cinematography, top notch VFX, Superb Production design and the powerful Maddock’s supernatural universe coming together giving chilling feels in the adrenaline pumping climax. Director Amar Kaushik yet again excels in brining out a unique and fun to watch horror comedy with the right balance leaving the audience completely entertained in the cinemas, the concept is well framed and presented, it was overwhelming feeling to see BHEDIYA,STREE and the the active cast in a single frame killing it . Climax was phenomenal To the next level. Rajkumar Rao hits the ball out of the park with his impeccable comic time and a strong performance throughout, Shraddha Kapoor delivered to the par excellence , whatta performance from her a silent avatar to the fierce avatar ,she just killed it gracefully and gorgeously. Great chemistry between the lead pair,Pankaj Tripati was Fun , Aparshakthi Khurana, Abhishek Banerjee entertains us throughout and all of them  in a combo brought out the best fun camaraderie making audience go gaga over . Anya Singh as chitti had a sweet and short role . This film teaches us how cameos need to be handled ,with Akshay Kumar in his zone delivering a Cameo to remember, followed by Varun Dhawan As Bhediya , Tammana as Shama
"""
review

'IN WHOLESOME ENTERTAINER,POORA PAISA VASOOL DHAMAKEDAR EXPERIENCE ,a perfect Horror comedy with all the elements right in place with horror comedy blend, Emotions, Fun , Great BGM , Excellent Cinematography, top notch VFX, Superb Production design and the powerful Maddock’s supernatural universe coming together giving chilling feels in the adrenaline pumping climax. Director Amar Kaushik yet again excels in brining out a unique and fun to watch horror comedy with the right balance leaving the audience completely entertained in the cinemas, the concept is well framed and presented, it was overwhelming feeling to see BHEDIYA,STREE and the the active cast in a single frame killing it . Climax was phenomenal To the next level. Rajkumar Rao hits the ball out of the park with his impeccable comic time and a strong performance throughout, Shraddha Kapoor delivered to the par excellence , whatta performance from her a silent avatar to the fierce avatar ,she just killed it gracefully and gorge

In [10]:
classification(review)

[{'label': 'POSITIVE', 'score': 0.9998418092727661}]

In [14]:
df.columns

Index(['label', 'tweet', 'cleaned_tweets', 'cleaned_tweets_without_stopwords'], dtype='object')

In [15]:
classification(df['cleaned_tweets'][25])

[{'label': 'POSITIVE', 'score': 0.9906250238418579}]

In [19]:
classification(df['cleaned_tweets'][2])

[{'label': 'POSITIVE', 'score': 0.9895538091659546}]

In [18]:
df['cleaned_tweets'][2]

'love this would you talk makememories unplug relax iphone smartphone wifi connect'